# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('a01', '0003_auto_20161025_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='per',
            name='age',
        ),
        migrations.RemoveField(
            model_name='per',
            name='name',
        ),
        migrations.AddField(
            model_name='per',
            name='summary',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='per',
            name='title',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='per',
            name='url',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
